version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
      - dependency-type: direct
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '> 12'
    versioning-strategy: increase
    commit-message:
      prefix: chore
      include: scope
